---
title: "p8105_hw5_yg2762"
author: "Yang Gao"
date: "11/11/2021"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
```

Problem 1

```{r}
homicide_df = 
  read.csv("./homicide-data.csv", na = c(" ", "Unknown")) %>% 
  mutate(city_state = str_c(city, state)) %>% 
  relocate(city_state) %>%
  mutate(
  resolution = case_when(
    disposition =="Closed without arrest" ~ "unsolved",
    disposition =="Open/No arrest" ~"unsolved",
    disposition =="Closed by arrest" ~ "solved")) %>% 
  relocate(city_state) %>% 
  filter(city_state !="TulsaAL")
```

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state =="BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolution =="unsolved"), n = n()
  )


baltimore_test = 
  prop.test(
    x = baltimore_summary %>%  pull(unsolved),
    n = baltimore_summary %>% pull(n)
  )

baltimore_test %>% 
  broom::tidy()
```

```{r}
prop_test_function = function(city_df){
  
  city_summary = 
  city_df %>% 
  summarize(
    unsolved = sum(resolution =="unsolved"), 
    n =n()
  )


city_test = 
  prop.test(
    x = city_summary %>%  pull(unsolved),
    n = city_summary %>% pull(n)
  )

return(city_test)
  
}
```


```{r}
result_df = 
  homicide_df %>% 
  nest(data = uid : resolution) %>% 
  mutate(
    test_result = map(data, prop_test_function),
    tidy_result = map(test_result, broom::tidy)
  ) %>% 
  select(city_state, tidy_result) %>% 
  unnest(tidy_result) %>% 
  select(city_state, estimate, starts_with("conf"))
```

```{r}
result_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90))
```


Problem 2
dataframe containing all file names
```{r}
file_names = 
  list.files (path = "./data", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
study_df = tibble (file_names)
```

```{r}
files = function (x) {
  read_file = read_csv(file = x)
}
```

```{r}
file_names = 
  list.files (path = "./data", pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
study_df = tibble (file_names)

data_path = "./data"

study_df = study_df %>% 
  mutate (file_contents = map(file_names, ~read_csv(file.path (data_path, .))))
```

```{r}
tidy_study_df = study_df %>% 
  unnest (cols = file_contents) %>% 
  separate(file_names, into = c("file_names", "."), sep = 6) %>%
  select(-.) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "value"
  ) 

ggplot(tidy_study_df, aes(x = week, y = value)) + 
  geom_line(aes(group = file_names, color = file_names), alpha=0.8)
```




Problem 3
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()
```

```{r}
fill = function(x) {
  
  if (is.numeric(x)) {x = ifelse(is.na(x), 
                            mean(x, na.rm = TRUE), 
                            x)} 
  else {x = ifelse (is.na(x), "virginica", x)}
  
}
```

```{r}
output = map(iris_with_missing, fill)

iris_no_missing = bind_rows(output)

iris_no_missing
```

